service: chess-bot

provider:
  name: aws
  runtime: nodejs4.3
#  stage: dev
  region: eu-west-1

functions:
  move:
    handler: web/move.handler
    memorySize: 1536
    timeout: 60
    events:
      - http:
          path: move
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                color: true
                fen: true
